### ISSUE TITLE
Transition from System View to Package View

### ISSUE THREAD

**Issue by phillima** [phillima/avisualizer#13]
**Context** 
- The System View provides a visualization with higher level details of annotation schemas per packages.
- If the users wishes to see more details from that package it should transition to the Package View.

**Feature**
- Allow the user to navigate from a package in the System View to the Package View without losing the reference and already zoomed in that specific package
- There should be a transition information/effect so that the user is aware that the view changed from System View to the Package View.

**Comment by pomba123** [comment]
Implemented the transition between views change.

**Comment by pomba123** [comment]
Implemented transition between views.

**Comment by phillima** [comment]
While in the System View, as soon as the user zooms in a package a menu (navigation bar) should appear at the left with the following information:
- The name of the root package (the one zoomed in).
- An option to switch to "Package View" (for the package zoomed in, i..e, the root package)
- A list of the inner packages. The user should also be able to zoom in these packages, and switch to Package View (from this list).

**Comment by phillima** [comment]
Previous feature (navigation bar) still unclear as how to proceed given the feedback we obtained from initial interviews

**Comment by phillima** [comment]
Closing the issue since requirements are still being discussed
