### ISSUE TITLE
Transition from Package View to Class View

### ISSUE THREAD

**Issue by phillima** [phillima/avisualizer#20]
Context

- The Package View provides a visualization with medium level details of annotation per classes inside packages.
This view also shows inner packages. If the users wishes to see more details from that package it should transition to the Class View.
- While in the Package View, to the left, there will be a navigation menu with the name of the classes/interfaces (types). 

Feature

- In the navigation menu on the left, the user will be able to chose a type (class/interface/etc) and zoom in for a Class View

**Comment by pomba123** [comment]
Added navigation menu v0.3.

**Comment by phillima** [comment]
Navigation from Package View to Class View implemented!
