### ISSUE TITLE
Visualization for the Class View

### ISSUE THREAD

**Issue by phillima** [phillima/avisualizer#3]
The AVisualizer should provide a visualization to expose the class inner structure based on some annotation metrics. This polymetric view will be a circle pack

Following is the view description

- The innermost circles are annotations. They should be colored  according to their schema. Their dimensions can be based on the following metrics AA or LOCAD. The tool should provide means to change between these two metrics.

**Comment by pomba123** [comment]
Added class view based on AA. Still need to implement chanve between AA and LOCAD
